### ISSUE TITLE
Roam is not Open Source

### ISSUE THREAD

**Issue by abhijitnandy** [everestpipkin/tools-list#19]
Under **Text editors & writing apps**, Roam is listed.

However, Roam is not open source

**Comment by daveloyall** [comment]
Neither are `Tumult Hype` nor `Screenotate`.

@everestpipkin I think you're not using that phrase as it is normally used.

I see that you joined Github in 2015 and your personal website has a neat retro-computing aesthetic.. so I won't presume you've never read this document.. http://www.gnu.org/philosophy/free-sw.html But I'd encourage you to look at it with fresh eyes.  Not to mention, it's been revised 39 times in the past five years.

Cheers,
--sebboh

**Comment by everestpipkin** [comment]
The list is an exclusive (tiny, experimental, free, OR open source) not inclusive list. Though I've made this clear on the website description, I've now updated the Github description to match.
